-- 017_seed_recipes.up.sql
-- Retired: recipe seeding now lives entirely in database/seeds/. The original
-- 30 inserts in this migration assigned UUIDs (a0000001-…010 = Paneer Tikka,
-- etc.) that collide with the seed files (a0000001-…010 = Vegetable Pulao),
-- which made the seeds unloadable on top of this migration. The migration
-- file is kept so the tracking sequence stays unbroken; new databases get
-- their recipes from database/seeds/.
--
-- If a database has the legacy 30 recipes left over from a prior run of this
-- migration, drop them before loading the seeds:
--   psql ... < database/migrations/017_seed_recipes.down.sql

-- (no-op)
